#!/usr/bin/env bash
#check if the correct number of parameters is provided
if [ "$#" != 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking for scp
SCP_COMMAND="scp -o StrictHostKeyChecking=no -i $ssh_key_path $file_path $username@$server_ip:~/"
$SCP_COMMAND
