#!/usr/bin/env bash
# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Create a backup of the original configuration file
#cp "$nginx_conf" "$nginx_conf.bak"

# Add a location block for redirection to the Nginx configuration

#new_server_block_content="location /redirect_me {return 301 http://example.com/new_page;}"
# Add the new content to the existing server block

sudo sed -i "/# SSL configuration/a\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" "$nginx_conf"

sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
