#!/usr/bin/env bash
# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

sudo sed -i "/^[[:space:]]*server {/a\\\tadd_header X-Served-By $(hostname);" "$nginx_conf"

sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
