#!/usr/bin/env bash
# Creating a tar backup file for sql databases
if [ $# -eq 1 ]; then
	MYSQL_PASSWORD="$1"
else
	MYSQL_PASSWORD=""
fi

# Generate the current date in the required format
DATE=$(date +"%d-%m-%Y")

# MySQL dump command
MYSQL_DUMP_CMD="mysqldump -u root -p${MYSQL_PASSWORD} --all-databases > backup.sql"

# Execute the MySQL dump command
eval "$MYSQL_DUMP_CMD"

# Compress the MySQL dump file
tar -czf "${DATE}.tar.gz" "backup.sql"
