#!/usr/bin/env bash
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Trap the SIGTERM signal and associate it with the handle_sigterm function
trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
