#!/usr/bin/env bash
# This script reads and formats information from /etc/passwd.

# Use a while loop to read lines from /etc/passwd
while IFS=: read -r username _ uid gid info home shell; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
