#!/usr/bin/env bash
# This script displays messages based on the loop iteration.

# Initialize a counter variable
counter=1

# Use a while loop to iterate from 1 to 10
while [ $counter -le 10 ]; do
	# Check the iteration number and display the corresponding message
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	# Increment the counter
	((counter++))
done
